name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{env.QUAYIO_USER}}
        DOCKER_PASS: ${{env.QUAYIO_PASS}}
      run: |
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
        docker build . --file Dockerfile --tag quay.io/joseph_yang_dev/ontario-vaccine-finder:$(date +%s)
